* riverpy

riverpy is a River of News aggregator written in Python.

When it all comes together, it looks like this:
http://river.davising.com/index.html

** Installation

=$ pip install git+https://github.com/edavis/riverpy#egg=riverpy=

** Running

=$ river -b S3-BUCKET SUBSCRIPTION-LIST-URL=

For example, here's how the above demo is generated:

=$ river -b river.davising.com -e 150 https://dl.dropboxusercontent.com/u/19853263/feeds.txt=

** Subscription Lists

At the core of riverpy are "subscription lists."

Subscription lists are files that contain URLs of RSS feeds. Each feed
belongs to a category. Adding feeds to this file is how you
"subscribe" to them.

riverpy accepts two kinds of subscription lists: plain text and OPML.

*Plain text* is the simpler of the two and recommended if you're
unsure which to use.

Here's an example of a plain text subscription list:
https://dl.dropboxusercontent.com/u/19853263/feeds.txt

The nice thing about this format is you only need a text editor (e.g.,
Notepad, TextEdit, etc.) to use it.

The format is quite simple. Each category has a name followed by a
colon. Then each feed for that category follows this format:

- two spaces
- a dash
- another space
- the URL

*OPML* is the other subscription list format accepted by riverpy.

OPML is a dialect of XML and not generally written by hand. Instead,
it's often generated by outliners or other programs.

Here's an example of an OPML subscription list:
http://projects.davising.com/riverpy/feeds.opml

The format is also pretty simple. Each top-level headline is a
category. The children of each top-level headline have type="rss" and
xmlUrl set to the RSS URL. Include nodes work (though only one level
deep.)

** Unfinished

- add option to spit out --json or --jsonp
- add option to write to local directory
- web: use permalinks

** License

BSD
